### PR TITLE
attempt to clarify the role of "special" teams when tagging

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Comment by jhoblitt** [comment]
@frossie @gcomoretto This is an attempt to clarify the intended tagging strategy but doesn't necessarily reflect the current state of affairs.  There are repos which are only members of `DM Auxillaries`, `DM Externals`, or `Data Management` while others have assorted combinations of the above (which I have been sorting out to avoid eups product<->aux tagging conflicts).  I think it would simply maters if users were removed completely from `DM Externals` and `DM Auxillaries` while `Data Management` is used to provide developer write access.

**Review by gcomoretto — APPROVED** [review]
OK.
Maybe the 14.0 in the above line should be made more general.

**Review by gcomoretto — APPROVED** [review]

**Review by gcomoretto — APPROVED** [review]

**Comment by jhoblitt** [comment]
@gcomoretto I don't know exactly what the intend of the `Tokens` subsection is.  It probably makes sense to remove it.  Its also confusing to have simple cleanups mixed in with this PR.  I've opened #3 to be pure "cleanups", including removal of the `Tokens` subsection, and will rebase this PR on top of that.

**Comment by jhoblitt** [comment]
rebased after the merge of #2

**Pull request merged**
